### ISSUE TITLE
Linux port

### ISSUE THREAD

**Issue by jedenastka** [FireFox2000000/Moonscraper-Chart-Editor#10]
Hi. I'm asking for Linux port for this project. It runs terribly under Wine, and Unity gives me compilation errors when I try to build it (I'm n00b in C#, so I don't know what's going on).

**Comment by bmwalters** [comment]
I've got a WIP Linux port running @ my fork https://github.com/bmwalters/Moonscraper-Chart-Editor/tree/zerf/linux

What works:
- charting

Current limitations:
- ogg files only
- no controller support
- a bunch of stuff is disabled

Other random notes before this can be shipped:
- build config should be cleaned up, with BASS libraries shipped for each platform
- this has very little testing. if there's something broken for a specific use-case I can take a look, but what works is the bare necessities right now.

**Comment by FireFox2000000** [comment]
@bmwalters Yeah, using the standalone file dialog is as far as I've gotten with a linux port. I haven't bothered looking further into it for the exact reasons you mentioned. If you can get the rest of those features working I'd be very happy to pull that into the main repo.

**Comment by dominuick** [comment]
Please port, i will give you my kidneys

**Comment by FireFox2000000** [comment]
I have pushed up a new branch to get a potential Linux build working over at https://github.com/FireFox2000000/Moonscraper-Chart-Editor/tree/linux_build. This branch includes all currently available plugins committed (there are still some that need to be found) as well as skeleton classes for the OS system specific stuff.

Attached at the root is a "LINUX TODO.txt", which is hopefully a guide containing everything that's required to get a linux build fully running without any corners cut. 

@bmwalters would you be interested in forking this new branch and following the guide to so if we can get this working? Due to various circumstances I can't get into Linux easily myself.

**Comment by dominuick** [comment]
I will help test and preview this build, i would love to see this as i have loved guitar/clone hero since they have come out i would also love to see this game on steam, and yes i know about copy rite reasons but it could be free and would support the steam workshop for extra songs and themes
chlauncher would also be good to see in the official game (clone hero)
