### ISSUE TITLE
Error building package from PKGBUILD

### ISSUE THREAD

**Issue by MineClashTV** [FireFox2000000/Moonscraper-Chart-Editor#42]
I've tried to install Moonscraper on Artix Linux (OpenRC, basically like Arch Linux, shouldn't matter).

makepkg stopped when it reached package(), as seen on this image:
![Screenshot from 2020-12-23 19-35-37](https://user-images.githubusercontent.com/30622888/103027595-748f8980-4556-11eb-99a2-b5a9e2f70eaf.png)

The faulty cp command is located at line 123. If you need any more info, let me know.

**Comment by FireFox2000000** [comment]
@bmwalters

**Comment by bmwalters** [comment]
In this case the problem is that this line https://github.com/FireFox2000000/Moonscraper-Chart-Editor/blob/529274a974615cf50bb6c278f5236889d397ae98/aur/PKGBUILD#L11 needs to be changed to the current Moonscraper version, since we use it to calculate the folder name. You can take a look in the `<build directory>/build` directory to double-check what the folder name is and make sure the version number matches it.

I'm pleasantly surprised you got the build to work since it uses an unusual method of providing the license file and building inside a sandbox.

**Comment by MineClashTV** [comment]
Yup, that fixed it.

_curpkgver needs to be changed to 1.3.5, after that it installs just fine.

**Comment by FireFox2000000** [comment]
Is there any way to automate this process? It's gonna be a bit tedious for me to have to manually change that file every time I want to bump the version number.

**Comment by bmwalters** [comment]
Will the folder name always be the same as the current git tag? If so then #45 should fix this.

**Comment by FireFox2000000** [comment]
Not for the test builds I send out on my Discord server, version number gets bumped a fair bit because of that. Version number will always be up to date in `Moonscraper Chart Editor/ProjectSettings/ProjectSettings.asset`, as per the `bundleVersion` value though.

**Comment by MineClashTV** [comment]
> Also just want to check I get the issue, is this when trying to make and run an MS build from source on a Unix machine?

Yes. It builds fine but just fails to copy the binary to the proper location because of the hardcored version mismatch

**Comment by bmwalters** [comment]
I pushed a similar change which now reads the version from `ProjectSettings.asset` to determine the build folder name.
